server:
  port: 8886

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_demo2?serverTimezone=UTC&useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
#    url: jdbc:mysql://localhost:3308/springboot_demo2?serverTimezone=UTC&useSSL=true&useUnicode=true&characterEncoding=UTF-8
#    username: text
#    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 10
      max-active: 100
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: ppg.demo.pojo

